// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxRs-qcABqE7Q6NROtIQL8BfzCKJmeoA',
    appId: '1:7346330417:web:81c9bc1cbf812d711f2e10',
    messagingSenderId: '7346330417',
    projectId: 'heybit---habit-tracking',
    authDomain: 'heybit---habit-tracking.firebaseapp.com',
    storageBucket: 'heybit---habit-tracking.firebasestorage.app',
    measurementId: 'G-FKS44LEFHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPN6m3b3PGJ9pt0710nTOTtWTxRIgQyn0',
    appId: '1:7346330417:android:50bcf9b47f119d461f2e10',
    messagingSenderId: '7346330417',
    projectId: 'heybit---habit-tracking',
    storageBucket: 'heybit---habit-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KrCyp50X0YTp36RNlk5FKaMm73FpC0A',
    appId: '1:7346330417:ios:60420b0b8e67cf901f2e10',
    messagingSenderId: '7346330417',
    projectId: 'heybit---habit-tracking',
    storageBucket: 'heybit---habit-tracking.firebasestorage.app',
    iosClientId: '7346330417-ectv96hbeb9a1ggoo4rjbrgcmf5m1hg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.heyBit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KrCyp50X0YTp36RNlk5FKaMm73FpC0A',
    appId: '1:7346330417:ios:60420b0b8e67cf901f2e10',
    messagingSenderId: '7346330417',
    projectId: 'heybit---habit-tracking',
    storageBucket: 'heybit---habit-tracking.firebasestorage.app',
    iosClientId: '7346330417-ectv96hbeb9a1ggoo4rjbrgcmf5m1hg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.heyBit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJxRs-qcABqE7Q6NROtIQL8BfzCKJmeoA',
    appId: '1:7346330417:web:0d7044b6f47890651f2e10',
    messagingSenderId: '7346330417',
    projectId: 'heybit---habit-tracking',
    authDomain: 'heybit---habit-tracking.firebaseapp.com',
    storageBucket: 'heybit---habit-tracking.firebasestorage.app',
    measurementId: 'G-H3JGB2KH16',
  );
}
